#!/usr/bin/env bun
/**
 * Writes the `.dev.vars` files `wrangler dev` reads, from the single `.env` at the root.
 *
 * Wrangler does not read `.env`, and keeping three copies of the same secrets by hand is
 * how a demo breaks at the worst moment. Run this after changing `.env`:
 *
 *   bun run dev:vars
 */

import { writeFileSync } from "node:fs";

// The paid endpoints are paid to the treasury; naming it twice in .env is a way for the
// two to drift apart.
process.env.X402_SELLER_ADDRESS ??= process.env.CIRCLE_TREASURY_ADDRESS;

const TARGETS: Array<{ path: string; keys: string[] }> = [
  {
    path: "apps/api/.dev.vars",
    keys: [
      "ARC_NETWORK",
      "ARC_TESTNET_RPC_URL",
      "DATABASE_URL",
      "PUBLIC_WEB_URL",
      "INTERNAL_API_KEY",
      "GITHUB_APP_ID",
      "GITHUB_APP_PRIVATE_KEY",
      "GITHUB_WEBHOOK_SECRET",
      "CIRCLE_API_KEY",
      "CIRCLE_ENTITY_SECRET",
      "CIRCLE_VERIFIER_WALLET_ID",
      "CIRCLE_TREASURY_WALLET_ID",
      "CIRCLE_VERIFIER_ADDRESS",
      "COMPLIANCE_MODE",
      "REQUIRE_AGENT_STAKE",
    ],
  },
  {
    path: "apps/x402/.dev.vars",
    keys: [
      "ARC_NETWORK",
      "ARC_TESTNET_RPC_URL",
      "DATABASE_URL",
      "X402_SELLER_ADDRESS",
      "X402_FACILITATOR_URL",
      "GITHUB_APP_ID",
      "GITHUB_APP_PRIVATE_KEY",
      "ANTHROPIC_API_KEY",
      "ANTHROPIC_BASE_URL",
    ],
  },
  {
    path: "apps/web/.dev.vars",
    keys: [
      "PUBLIC_API_URL",
      "INTERNAL_API_KEY",
      "AUTH_SECRET",
      "AUTH_GITHUB_ID",
      "AUTH_GITHUB_SECRET",
    ],
  },
];

for (const target of TARGETS) {
  const lines = target.keys
    .map((key) => [key, process.env[key]] as const)
    .filter(([, value]) => value !== undefined && value !== "")
    .map(([key, value]) => `${key}=${JSON.stringify(value)}`);

  writeFileSync(
    target.path,
    `# Generated by "bun run dev:vars" from .env. Do not commit.\n${lines.join("\n")}\n`,
    {
      mode: 0o600,
    },
  );
  console.log(`${target.path}  ${lines.length} values`);
}
